import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import KeywordInput from "../components/KeywordInput";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>GossipGirl</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Gossip<span className="text-pink-300">Gurl</span>
        </h1>
        <p className="text-2xl text-gray-700">
          A Twitter Scraper with Sentiment Analysis
        </p>
        <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-3 lg:w-2/3"></div>
        <KeywordInput />
      </main>
    </>
  );
};
export default Home;
